#? Config file for btop v. 1.2.13

#* Name of theme file (if any), located in various locations...
#* In this repo, provided in themes/catppuccin_mocha.theme
color_theme = "catppuccin_mocha"

#* If the theme set in color_theme isn't found, try setting this to true to force download of theme from repository
theme_background = False

#* Set to True to enable "TrueColor" support (24bit colors)
truecolor = True

#* Set to True to force tty mode regardless if a real tty has been detected or not
force_tty = False

#* Define a custom list of presets
presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"

#* Set to True to enable vim keys for navigation
vim_keys = True

#* Set to True to enable rounded corners on boxes
rounded_corners = True

#* Amount of milliseconds between updates (warning: setting lower than 100ms may cause high cpu usage)
update_ms = 2000

#* Symbol used for graphs, valid: "braille", "block", "tty"
graph_symbol = "braille"
